# Generated by Django 4.2.7 on 2023-12-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendormanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending')),
                ('quality_rating', models.FloatField(blank=True, default=None, null=True)),
                ('issue_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('acknowledgement_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendormanagement.vendor')),
            ],
            options={
                'verbose_name': 'PurchaseOrder',
                'verbose_name_plural': 'PurchaseOrders',
            },
        ),
    ]
