# Generated by Django 4.2.7 on 2023-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('contact_details', models.TextField(default=None)),
                ('address', models.TextField(default=None)),
                ('vendor_code', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('on_time_delivery_rate', models.FloatField(blank=True, default=None, null=True)),
                ('quality_rating_avg', models.FloatField(blank=True, default=None, null=True)),
                ('average_response_time', models.FloatField(blank=True, default=None, null=True)),
                ('fulfillment_rate', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
